---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
     matchLabels:
         app: mysql
  strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 0
         maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        name: mysql-server
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
          - containerPort: 3306
          resources:
                 limits:
                    cpu: 500m
                 requests:
                    cpu: 500m
          env:
          - name: MYSQL_USER
            value: user_name
          - name: MYSQL_PASSWORD
            value : user_pass
          - name: MYSQL_ROOT_PASSWORD
            value: root_pass
          - name: MYSQL_DATABASE
            value: "database-name"
          - name: MYSQL_DATABASE
            value: "database-name-for-rancher"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-mysql
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysql-server
  targetCPUUtilizationPercentage: 80
