---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
      run: tomcat
    name: tomcat
spec:
   replicas: 2
   selector:
     matchLabels:
         run: tomcat
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 0
         maxUnavailable: 1
   minReadySeconds: 5
   revisionHistoryLimit: 5
   template:
      metadata:
        labels:
          run: tomcat
      spec:
        containers:
           - image: cssp007143/custom-image
             name:  tomcat
             resources:
                 limits:
                    cpu: 100m
                 requests:
                    cpu: 100m


---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  type: NodePort
  ports:
    - nodePort: 32222
      port: 8080
      targetPort: 8080
  selector:
    run: tomcat

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-httpd
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcat
  targetCPUUtilizationPercentage: 80
